# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  pull_request:
    branches: [ "trunk" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: |
        echo PR_Number=${{ github.event.number }} > .env
        echo PAT=aYzGrg8zADq8yrxqwpnuekNRDQZC2T3A7w3Y >> .env
        echo dataset_id=${{ vars.DATASET_ID }} >> .env
        echo uname=${{ vars.USERNAME }} >> .env
        echo pass=${{ vars.PASSWORD }} >> .env
        echo client_id=${{ vars.CLIENT_ID }} >> .env
        echo client_secret=${{ vars.CLIENT_SECRET }} >> .env
        echo refreshInterval=${{ vars.REFRESHINTERVAL }} >> .env
        ant -noinput -buildfile build.xml
